### PR TITLE
Alert component completed.

### PR DESCRIPTION
**Pull request by TJain02**
Here is the screenshot of the output from the live counter!
Screenshot (99)

### CODE REVIEW

**Review by sakshi006 — CHANGES_REQUESTED** [review]
You haven't added the iframes?
Rest is good.

**Review by Asuraking1n — COMMENTED** [review]
I suggest you should add some border radius it will be good. Other things are cool

**Comment by TJain02** [comment]
> 

Thank you for the suggestions Sakshi!

**Comment by TJain02** [comment]
> I suggest you should add some border radius it will be good. Other things are cool

Thank you for the suggestions! I'll surely work on it!

**Comment by TJain02** [comment]
> You haven't added the iframes? Rest is good.

Thank you for the suggestions! I'll surely look into it!

**Pull request merged**
